// TODO : 
// 0. Removing the  direct  wpm calculation from client --> server--> client(playerlist) 
// 1. while  running  the game user should see the wpm  generated by  the client server,  broadcasted  by backend server
// 2. after  finishing  the race :  show different page  of  result with  actual  value  of  wpm generated by the server 
// 3. then  save  it  in  user's  profile 
// 4. delete the  room .


import React from "react";
import { useRoomSocket } from "../../hooks/useRoomSocket";

const PlayersList = ({ playerProgress = {} }) => {
  const { socket, users, playerProgress: contextProgress } = useRoomSocket();
  const socketId = socket?.id;
  const progressSource =
    playerProgress && Object.keys(playerProgress).length > 0
      ? playerProgress
      : contextProgress || {};

  const playersWithProgress = users.map((user) => {
    const progress = progressSource[user.id] || {};
    return {
      ...user,
      ...progress,
    };
  });

  return (
    <div className="max-w-4xl mx-auto mb-6">
      <div className="bg-neutral-900/80 backdrop-blur-sm rounded-lg border border-neutral-800 p-4">
        <h3 className="text-sm font-medium text-neutral-400 mb-3 uppercase tracking-wider">
          Live Progress
        </h3>
        <div className="space-y-2">
          {playersWithProgress.length === 0 && (
            <div className="text-sm text-neutral-500 text-center py-4">
              No players connected
            </div>
          )}

          {playersWithProgress.map((player) => {
            const isSelf = socketId && player.id === socketId;
            const progress = player.progress || 0;
            const wpm = player.wpm || 0;
            const accuracy = player.accuracy || 100;
            const errors = player.errors || 0;
            const finished = player.finished;

            return (
              <div
                key={player.id}
                className={`player-row flex items-center gap-4 p-3 rounded-lg border transition-all ${
                  isSelf
                    ? "bg-blue-500/10 border-blue-500/30"
                    : "bg-neutral-800/50 border-neutral-700/50"
                } ${finished ? "opacity-75" : ""}`}
              >
                <div className="w-32 text-sm font-medium truncate text-white">
                  {isSelf ? `${player.name} (You)` : player.name}
                  {player.isOwner && (
                    <span className="ml-2 text-xs text-amber-400">👑</span>
                  )}
                </div>

                <div className="w-20 text-xs text-yellow-400 font-semibold">
                  {wpm} WPM
                </div>

                <div className="w-20 text-xs text-green-400">
                  {accuracy.toFixed(1)}% acc
                </div>

                <div className="w-16 text-xs text-red-400">
                  {errors} err
                </div>

                <div className="flex-1">
                  <div className="w-full bg-neutral-700 rounded-full h-2.5 overflow-hidden">
                    <div
                      className={`h-full transition-all duration-150 ${
                        finished ? "bg-emerald-500" : isSelf ? "bg-blue-500" : "bg-neutral-500"
                      }`}
                      style={{
                        width: `${Math.min(100, Math.max(0, progress))}%`,
                      }}
                    />
                  </div>
                </div>

                <div className="w-12 text-right text-xs text-neutral-400">
                  {finished ? "✓" : `${Math.round(progress)}%`}
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
};

export default PlayersList;
